name       : libmediainfo
version    : '19.04'
release    : 15
source     :
    - https://old.mediaarea.net/download/source/libmediainfo/19.04/libmediainfo_19.04.tar.xz : 8275f3031d63cea7b227437ac4222bc9709f434e233e5f32a533fcf405dd22fb
license    : BSD-2-Clause
component  : multimedia.library
summary    : A convenient unified display of the most relevant technical and tag data for video and audio files.
description: |
    A convenient unified display of the most relevant technical and tag data for video and audio files.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libmms)
    - pkgconfig(libzen)
setup      : |
    cd Project/GNU/Library
    %autogen --enable-shared --disable-static \
        --with-libcurl \
        --with-libmms
build      : |
    %make -C Project/GNU/Library
install    : |
    %make_install -C Project/GNU/Library
    install -Dm00644 Project/GNU/Library/libmediainfo.pc $installdir/%libdir%/pkgconfig/libmediainfo.pc
