name       : libmediainfo
version    : '19.07'
release    : 16
source     :
    - https://old.mediaarea.net/download/source/libmediainfo/19.07/libmediainfo_19.07.tar.xz : 5acbe3f0a48e10cacb588381454f30149c947ffa89659680165ed1a0603d6d4c
license    : BSD-2-Clause
component  : multimedia.library
summary    : A convenient unified display of the most relevant technical and tag data for video and audio files.
description: |
    A convenient unified display of the most relevant technical and tag data for video and audio files.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libmms)
    - pkgconfig(libzen)
setup      : |
    cd Project/GNU/Library
    %autogen --enable-shared --disable-static \
        --with-libcurl \
        --with-libmms
build      : |
    %make -C Project/GNU/Library
install    : |
    %make_install -C Project/GNU/Library
    install -Dm00644 Project/GNU/Library/libmediainfo.pc $installdir/%libdir%/pkgconfig/libmediainfo.pc
