name       : libmediainfo
version    : 0.7.91
release    : 3
source     :
    - https://mediaarea.net/download/source/libmediainfo/0.7.91/libmediainfo_0.7.91.tar.xz : 28818b88cedc8d5bc6b6c2a32d37ec456cb9784b4bf105416ef1e5821a6769c0
license    : BSD-2-Clause
component  : multimedia.library
summary    : A convenient unified display of the most relevant technical and tag data for video and audio files.
description: |
    A convenient unified display of the most relevant technical and tag data for video and audio files.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libmms)
    - pkgconfig(libzen)
setup      : |
    cd Project/GNU/Library
    %autogen --enable-shared --disable-static \
        --with-libcurl \
        --with-libmms
build      : |
    cd Project/GNU/Library
    %make
install    : |
    cd Project/GNU/Library
    %make_install
    install -Dm00644 libmediainfo.pc $installdir/%libdir%/pkgconfig/libmediainfo.pc
