name       : libmediainfo
version    : 0.7.98
release    : 7
source     :
    - https://mediaarea.net/download/source/libmediainfo/0.7.98/libmediainfo_0.7.98.tar.xz : c442ff8e179ef0611f9af38cff550255f3307f787a03d065d14d7d6300bc05dc
license    : BSD-2-Clause
component  : multimedia.library
summary    : A convenient unified display of the most relevant technical and tag data for video and audio files.
description: |
    A convenient unified display of the most relevant technical and tag data for video and audio files.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libmms)
    - pkgconfig(libzen)
setup      : |
    cd Project/GNU/Library
    %autogen --enable-shared --disable-static \
        --with-libcurl \
        --with-libmms
build      : |
    cd Project/GNU/Library
    %make
install    : |
    cd Project/GNU/Library
    %make_install
    install -Dm00644 libmediainfo.pc $installdir/%libdir%/pkgconfig/libmediainfo.pc
